// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using blogSitesi.DB;

#nullable disable

namespace blogSitesi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240731122949_seedBlogpostTable")]
    partial class seedBlogpostTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("blogSitesi.Models.BlogPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("BlogPosts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Evren yıllardır sıragelen sırlar tohumunun bir özüdür",
                            CreatedDate = new DateTime(2024, 7, 31, 15, 29, 49, 40, DateTimeKind.Local).AddTicks(6601),
                            ImagePath = "https://picsum.photos/200",
                            Title = "Evrenin sırrı",
                            UpdatedDate = new DateTime(2024, 7, 31, 15, 29, 49, 40, DateTimeKind.Local).AddTicks(6602)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
